### ISSUE TITLE
手指快速滑动时会报错

### ISSUE THREAD

**Issue by Lindroy** [maning0303/MNImageBrowser#1]
当手指快速缩放图片时，会报如下的错误： java.lang.IllegalArgumentException pointerIndex out of range。搜了一下，网上的解决方法基本都是在ViewPager的事件分发中捕获该异常。希望能解决一下，谢谢了。

**Comment by maning0303** [comment]
@Lindroy  好的，感谢反馈，我会尽快处理一下！

**Comment by maning0303** [comment]
@Lindroy 这边最新代码提交了版本V1.0.3 ,你去看看最新的，已经修改了这个问题

**Comment by Lindroy** [comment]
好的，谢谢了。
