### ISSUE TITLE
NullPointerException 

### ISSUE THREAD

**Issue by carozhu** [maning0303/MNImageBrowser#12]
Exception: Unable to start activity ComponentInfo{com.zsyj.habitcheckin/com.maning.imagebrowserlibrary.MNImageBrowserActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.maning.imagebrowserlibrary.model.ImageBrowserConfig.isFullScreenMode()' on a null object reference

空指针异常。看下

**Comment by maning0303** [comment]
@carozhu imageBrowserConfig.setFullScreenMode(fullScreenMode); 看看代码这个字段怎么设置的？ Demo有没有这样的问题呢？

**Comment by maning0303** [comment]
@carozhu 新版本发布了，你可以试试新版本。不会出现这个异常的。
