### ISSUE TITLE
可以多次打开MNImageBrowserActivity 从而导致crash

### ISSUE THREAD

**Issue by xuhaoyang** [maning0303/MNImageBrowser#13]
如题

建议改成 android:launchMode="singleTask"

**Comment by maning0303** [comment]
@xuhaoyang 感谢反馈，你先做一个防止多次连续点击，后面我优化一下这个问题。

**Comment by maning0303** [comment]
@xuhaoyang 新版本发布了，我内部加了连点过滤。请加入新版本
