### ISSUE TITLE
发现了 NullPointer异常！

### ISSUE THREAD

**Issue by YuShanMuGong** [maning0303/MNImageBrowser#14]
![image](https://user-images.githubusercontent.com/13248312/53460055-c52b1e00-3a76-11e9-8a63-78cd0df36134.png)

异常发生在 `298` 行，这里的 `imageBrowserConfig` 引用是一个 `NULL`，如图，我发现！这里先 调用了 `finish()` 方法，执行之后，在 `onDestory()` 中将 `imageBrowserConfig` 设置为 `NULL` 了，可能是这里的问题。

**Comment by YuShanMuGong** [comment]
???

**Comment by maning0303** [comment]
@YuShanMuGong 感谢反馈，会尽快修复这个问题的。

**Comment by maning0303** [comment]
@YuShanMuGong 问题已经修复，发布新版本了，请更新。
