### ISSUE TITLE
自定义遮掩层的时候，使用半透明背景没有效果

### ISSUE THREAD

**Issue by m511386374** [maning0303/MNImageBrowser#17]

**Comment by maning0303** [comment]
@m511386374 请问下自定义遮罩的背景是不是tools:background="#000000" tools这个标签只会在预览的时候起作用，看看我的Demo里面的

**Comment by m511386374** [comment]
![image](https://user-images.githubusercontent.com/19544200/62274921-662d6300-b473-11e9-8a86-bdb154c98bae.png)
![image](https://user-images.githubusercontent.com/19544200/62274929-6b8aad80-b473-11e9-97ba-c285c6f091eb.png)
![image](https://user-images.githubusercontent.com/19544200/62274937-6fb6cb00-b473-11e9-8dd2-612c7afe2177.png)
背景还是黑色的，这个就是你的demo我设置的是半透明，就算我设置白色也没有用
![image](https://user-images.githubusercontent.com/19544200/62275033-a12f9680-b473-11e9-8f20-6ebd1e96a93a.png)
最终效果还是黑色

**Comment by m511386374** [comment]
@maning0303

**Comment by maning0303** [comment]
@m511386374 不能用tools：xxxx(tools这个标签你可以去搜索一下用法),换成android:background="",换成android:background="",换成android:background=""

**Comment by maning0303** [comment]
@m511386374  tools：只会在预览的时候起作用，运行到手机上是没有作用的。
删掉tools:background=""
删掉tools:background=""
删掉tools:background=""
