### ISSUE TITLE
Android 8.0 设置竖屏crash

### ISSUE THREAD

**Issue by samgsmg** [maning0303/MNImageBrowser#19]

**Comment by maning0303** [comment]
@samgsmg 请问一下有没有相关的crash日志呢？贴出来看一下

**Comment by samgsmg** [comment]
原因是这个:  
java.lang.IllegalStateException: Only fullscreen activities can request orientation
当你在一个“translucent”的Activity里，试图执行setRequestedOrientation的时候就会触发这个异常。

在不改MNIMageBrowser 包的情况下，此问题无解，
我用添加style适配的方法改了，即在 8.0中用 windowIsTranslucent=false,其它用 windowIsTranslucent=true.   8.0用效果差一点而己，不会crash

**Comment by maning0303** [comment]
@samgsmg 感谢，我看看这个，我记得这个问题之前修改过相关的东西。

**Comment by samgsmg** [comment]
我app中  引用的 androidx 的库，你看看跟这个有没有关系？
implementation 'androidx.appcompat:appcompat:1.0.2'

**Comment by maning0303** [comment]
@samgsmg 应该和这个没有关系的，我想了下也没有什么好的解决方案，只能8.0的设置单独的主题，9.0官方又去掉了限制，所以只有8.0手机会出现。

**Comment by maning0303** [comment]
@samgsmg 方便加一下微信吗？我这边手机系统都升级了，没有看到8.0手机。帮忙做一下测试。13237110231

**Comment by maning0303** [comment]
@samgsmg 新版本发布，修复这个问题，感谢配合。👍👍👍
