### ISSUE TITLE
三星S8上面下滑关闭不可用

### ISSUE THREAD

**Issue by kevin321happy** [maning0303/MNImageBrowser#20]
在三星的s8上面查看图片无法下滑关闭，其他手机可以

**Comment by maning0303** [comment]
@kevin321happy 是不是8.0的系统呢，8.0为了规避一个（fullscreen opaque activities can request orientation）bug去掉了下滑缩小功能。

**Comment by kevin321happy** [comment]
嗯  是8.0的

**Comment by maning0303** [comment]
@kevin321happy 这是没有问题的，设计到8.0一个bug的适配，要是有什么好的方案可以提供讨论一下。

**Comment by maning0303** [comment]
@kevin321happy 我先关闭这个 issues了，有什么问题再提出来，感谢反馈。
