### ISSUE TITLE
 requestFeature() must be called before adding content

### ISSUE THREAD

**Issue by caiyoufei** [maning0303/MNImageBrowser#24]
Caused by: android.util.AndroidRuntimeException: requestFeature() must be called before adding content
![image](https://user-images.githubusercontent.com/11989916/67658133-4e3e8000-f98b-11e9-9878-4161375fbd4e.png)
测试手机：
魅蓝5S
安卓6.0
使用的是Androidx :V1.2.3X

**Comment by caiyoufei** [comment]
![image](https://user-images.githubusercontent.com/11989916/67658519-5f3bc100-f98c-11e9-95cd-ff3033892fc4.png)

**Comment by maning0303** [comment]
@caiyoufei 感谢反馈，我会尽快确认修复这个问题的。

**Comment by maning0303** [comment]
@caiyoufei 最新版本已优化这个问题，你可以去更新最新版本，有什么问题再反馈。
