### ISSUE TITLE
能否支持长图呢？

### ISSUE THREAD

**Issue by VliceZ** [maning0303/MNImageBrowser#25]
现在长图用的比较多的有[SubsamplingScaleImageView](https://github.com/davemorrissey/subsampling-scale-image-view)，能不能在判断是长图（bitmap.height > screenHeight）的时候默认切换到这个view来显示长图呢？

**Comment by VliceZ** [comment]
> 现在长图用的比较多的有[SubsamplingScaleImageView](https://github.com/davemorrissey/subsampling-scale-image-view)，能不能在判断是长图（bitmap.height > screenHeight）的时候默认切换到这个view来显示长图呢？

**Comment by maning0303** [comment]
@VliceZ 现在我Demo里面也有长图显示，有什么不能满足的地方吗？

**Comment by zzmingo** [comment]
不是针对谁，在座的都不够长，（狗头

![mp weixin qq com-20200630_201438](https://user-images.githubusercontent.com/24818119/86198959-6c4c2800-bb8b-11ea-940a-1b1261d59163.png)

**Comment by maning0303** [comment]
@zzmingo 我错了 ，你的最长 .....

**Comment by zzmingo** [comment]
@maning0303 问题可能在这，你的测试长图尺寸没有超过Android的bitmap的max size

**Comment by maning0303** [comment]
@VliceZ @zzmingo 我尽快测试安排上 ，感谢反馈哈

**Comment by maning0303** [comment]
@VliceZ @zzmingo 最新版本支持自定义图片显示View，支持Fresco，SubsamplingScaleImageView等想自己实现的展示图片，具体可以参考Demo中Fresco配置。有什么使用问题在反馈回来。感谢。
