### ISSUE TITLE
AndroidX 通过gradle依赖后编译报错

### ISSUE THREAD

**Issue by GokHoLee** [maning0303/MNImageBrowser#26]
如果项目中导入了 Material Design(com.google.android.material:material:1.1.0) 包的话, 编译会出现异常
![image](https://user-images.githubusercontent.com/47957704/84015290-3366cc00-a9ae-11ea-8dd8-20c6558d4afe.png)
从编译结果可以发现是ci_orientation 以及 ci_gravity 自定义属性引发了异常了

**Comment by maning0303** [comment]
@GokHoLee 我试一下看看具体问题，感谢反馈

**Comment by maning0303** [comment]
@GokHoLee 最新版本去掉了attrs,麻烦试一下最新版本包V1.3.0X，感谢反馈。
