### ISSUE TITLE
小米8开启经典导航键后，下拉关闭显示问题

### ISSUE THREAD

**Issue by wqjuser** [maning0303/MNImageBrowser#27]
小米8手机开启经典导航键后，下拉关闭时底部会多出一条黑色的矩形框一起跟随图片消失

**Comment by maning0303** [comment]
@wqjuser 下个版本修复这个问题

**Comment by maning0303** [comment]
@wqjuser 新版本V1.3.5版本已经发布了，修复了这个问题，请及时升级，有什么问题再提出来，感谢反馈。
