### ISSUE TITLE
关于显示一张图片时的问题

### ISSUE THREAD

**Issue by Lindroy** [maning0303/MNImageBrowser#3]
作者你好，我在自己的项目中有时会用到MNImageBrowser来显示一张图片，因此想提几点建议：

1. 可以增加一个方法，只有一张图片时`showImageBrowser`方法的数据源参数可以只传一个图片路径（字符串），不用传集合；

2. 增加重力感应功能（可以自行开启和关闭），方便旋转屏幕查看某些宽度较大的图片。

如果有时间的话，可以考虑一下上面的功能。另外，也感谢你对我上个的问题的解决。

**Comment by maning0303** [comment]
@Lindroy 感谢提出的问题和建议，新版本单张图片还是需要用集合传递（这样就不用区分单张和多张显示的时候调用不同的方法，更加统一，个人理解），只是不会显示下面数量指示器，至于重力感应这个后期可以考虑一下！ 感谢
