### ISSUE TITLE
如何实时更新数据呢？

### ISSUE THREAD

**Issue by jldaii** [maning0303/MNImageBrowser#8]
如果我在浏览的时候，删掉了一个列表中的一个图片，怎么去更新呢？

**Comment by maning0303** [comment]
@jldaii 暂时还没有这个功能，这个下个版本一起优化，感谢反馈。

**Comment by maning0303** [comment]
@jldaii 新版本已经更新了，可以动态删除图片了，具体的看一下Demo和README。感谢提出的问题

**Comment by jldaii** [comment]
好的 谢谢你。  我会持续关注。
